### ISSUE TITLE
Missing Dataset

### ISSUE THREAD

**Issue by PierreColombo** [TIGER-AI-Lab/StructLM#1]
Hello,
Thanks a lot for your nice work.
I'm trying to better understand the data sources. There is a link that is given on the main website but the link seems to be missing: https://huggingface.co/datasets/TIGER-Lab/SKGInstruct.
Ist there any plan to release the IFT dataset?
Cheers

**Comment by wenhuchen** [comment]
Hi there, thanks for raising this. We already make it public. The data will be there soon.

**Comment by azhx** [comment]
Dataset is now public. Thanks! https://huggingface.co/datasets/TIGER-Lab/SKGInstruct

**Comment by PierreColombo** [comment]
Brillaint !

**Comment by kanseaveg** [comment]
@azhx When will the test set be made public? The test set can verify whether structLM is useful, I want to know if it's useful.
