### ISSUE TITLE
Training scripts

### ISSUE THREAD

**Issue by vdeepak13** [TIGER-AI-Lab/StructLM#11]
Is the plan to open-source the training scripts too?

**Comment by azhx** [comment]
Hi, you can currently use the dataset in the llama factory repo. https://github.com/hiyouga/LLaMA-Factory

Let me know if that helps. I can provide training scripts if still needed.

**Comment by vdeepak13** [comment]
Adding the training scripts with some instructions to reproduce training pipelines would be helpful :)

**Comment by azhx** [comment]
Hi, I just added the steps in the readme for what I believe is the easiest way to reproduce. Let me know if you have any issues!
