### ISSUE TITLE
Training script for StructLM-7B-Mistral.

### ISSUE THREAD

**Issue by YaooXu** [TIGER-AI-Lab/StructLM#12]
Could you please provide the training script for StructLM-7B-Mistral? As I find there is a difference between the format of training data https://huggingface.co/datasets/TIGER-Lab/SKGInstruct-skg-only and test data skginstruct_test_file_mistral.json.

E.g., for the WTQ dataset,
Input format of training data
![image](https://github.com/TIGER-AI-Lab/StructLM/assets/44971199/c9baab26-8516-4054-b304-12f985ee167e)

Input format of test data
![image](https://github.com/TIGER-AI-Lab/StructLM/assets/44971199/86e7d4ff-2591-4c04-8cee-fe9e88b39280)

There is no "### Response:\n" in the training dataset. Is there an anthor data preprocessing script in the training of StructLM-7B-Mistral?

**Comment by wenhuchen** [comment]
Hi there, we use stanford Alpaca training script to train it. So it follows the alpaca prompt format. The library we are using is here at https://github.com/tatsu-lab/stanford_alpaca.

**Comment by YaooXu** [comment]
I got it, thanks for your replay!
