### ISSUE TITLE
Update for the StructLM-7B

### ISSUE THREAD

**Issue by YaooXu** [TIGER-AI-Lab/StructLM#13]
Hi, I also can't reproduce the test results of StructLM-7B, which is first mentioned in issue https://github.com/TIGER-AI-Lab/StructLM/issues/8. 

Could you update the checkpoints files of StructLM-7B, as I want to do some comparison experiments in my paper, thanks a lot!

**Comment by wenhuchen** [comment]
I think Alex lost the checkpoint for some reason. Would you mind comparing against Mistral version? https://huggingface.co/TIGER-Lab/StructLM-7B-Mistral

**Comment by YaooXu** [comment]
It's a pity, as I want to do some further experiments on llama-7b, 13b and 70b. Could you provide the training args of training StructLM-7B-Mistral with [stanford_alpaca](https://github.com/tatsu-lab/stanford_alpaca)? So I can retrain a new StructLM-7B with the same setting as StructLM-7B-Mistral.

**Comment by azhx** [comment]
Hi, I just added steps in the readme for reproducing the training process. You can reference the hyperparams in `StructLM_finetuning.yaml` for reference in other training frameworks also. Let me know if you have any issues!

**Comment by YaooXu** [comment]
Thanks a lot!
