### ISSUE TITLE
Training Dataset With More Information

### ISSUE THREAD

**Issue by YaooXu** [TIGER-AI-Lab/StructLM#14]
Hi, could you please provide training set with the similar format like testing set, which includes table, table_id and so on? 
![image](https://github.com/TIGER-AI-Lab/StructLM/assets/44971199/28ee171f-a80a-4d88-b24b-871ab092248a)

As I want to some experiment with adjusted training set, I tried to parse table from the training set, but there are many tables that cannot be parsed properly due to truncating or delimiter issues.

Thanks a lot!

**Comment by azhx** [comment]
Sure, I can generate this for you. Please give me a few days.

In the meantime, you can use some of the raw data found here https://drive.google.com/drive/u/0/mobile/folders/1GXigUv3MU-Sh4XiY6Wz3xVeNT_s0SuON

Alex
