### ISSUE TITLE
Incomplete eval data + cannot reproduce all

### ISSUE THREAD

**Issue by flbbb** [TIGER-AI-Lab/StructLM#16]
Hi,
Great work and thanks for sharing this.

Seems like some eval data are missing in the download link. Below are the tasks where the data are missing:

```
spider_with_cell
kvret
sparc_with_cell
compwebq
multiwoz
cosql_with_cell
cosql_with_cell
```
For these ones I checked and I didn't find the needed files in my download folder. Could you check if that is the case?

Then, for this task I cannot reproduce the results with StructLM-7B and by far, so I suspect a bug:
bird 0 accuracy

FYI here is my full evaluation results of your checkpoint, having run the generation with vllm on nvidia A100. Some are a bit above your reported figures, some are lower (ex: mmqa 10 points below what your reported).

Edit: I use a bit newer versions of your requirements, namely:
vllm 0.4.3
torch 2.2.0
accelerate 0.30.1
transformer 4.41.2
I didn't install xformers, as well as some parts of your requirements like lit, megablock.

Edit2: For dart I modified the implementation to compute the BLEU without pre-tokenization since it gave me errors, so this is not comparable to your reported results.
```
{
  'tabmwp.cfg/acc': 0.3911,
  'totto.cfg/sacrebleu': 0.4944,
  'grailqa.cfg/exact_match': 0.8027,
  'sql2text.cfg/blec': 0.9420,
  'mmqa.cfg/acc': 0.6842,
  'mmqa.cfg/f1': 0.7706,
  'spider_with_cell.cfg/error': 0,
  'kvret.cfg/error': 0,
  'hybridqa.cfg/acc': 0.4241,
  'hybridqa.cfg/f1': 0.5491,
  'sparc_with_cell.cfg/error': 0,
  'compwebq.cfg/acc': 0.7720,
  'compwebq.cfg/F1': 0.8498,
  'compwebq.cfg/Hits@1': 0.8725,
  'tab_fact.cfg/all': 0.8084,
  'tab_fact.cfg/simple': 0.9127,
  'tab_fact.cfg/complex': 0.7579,
  'tab_fact.cfg/small_test': 0.8308,
  'wikitq.cfg/all_ex': 0.2804,
  'wikisql.cfg/all_ex': 0.5084,
  'fetaqa.cfg/sacrebleu': 0.3594,
  'feverous.cfg/all': 0.8429,
  'multiwoz.cfg/error': 0,
  'dart.cfg/sacrebleu': 0.4434,
  'logic2text.cfg/blec': 0.8901,
  'mtop.cfg/exact_match': 0.8119,
  'mtop.cfg/template_accuracy': 0.8732,
  'bird.cfg/simple_acc': 0.0,
  'bird.cfg/moderate_acc': 0.0,
  'bird.cfg/challenging_acc': 0.0,
  'bird.cfg/acc': 0.0,
  'cosql_with_cell.cfg/error': 0,
  'sqa.cfg/all_acc': 0.3334,
  'sqa.cfg/pos_0_acc': 0.4244,
  'sqa.cfg/pos_1_acc': 0.2217,
  'sqa.cfg/pos_2_acc': 0.3607,
  'sqa.cfg/pos_3_acc': 0.3624,
  'sqa.cfg/interaction_acc': 0.0780,
  'webqsp.cfg/F1': 0.0,
  'infotabs.cfg/acc': 0.5531,
  'wikitabletext.cfg/sacrebleu': 0.0817,
  'finqa.cfg/acc': 0.2197,
  'avr': 0.4407
}
```

**Comment by azhx** [comment]
> Re: Reproducibility

Hi, for the reproducibility issue, please take a look at this 
https://github.com/TIGER-AI-Lab/StructLM/issues/8

It's really unfortunate but it seems like the checkpoint I uploaded for 7B was incorrect, and due to some accident the original checkpoints were wiped from our server. 

To amend this, we trained another 7B model based on Mistral which performs better overall. We have checked Mistral-7B, 13B, and 34B for reproducibility. 


> Re: data missing

Could you please share how you downloaded the data? Did you use the download script which downloads from huggingface? I see you have `cosql_with_cell` listed twice, so I'm not sure what that means. 


Thanks, 
Alex
