### ISSUE TITLE
Missing Configure files. Can you share the `Salesforce` configuration folder? I can't find it on the repository. Thank you.

### ISSUE THREAD

**Issue by kanseaveg** [TIGER-AI-Lab/StructLM#3]

**Comment by azhx** [comment]
Hi, I reorganized the whole repo. I'll write up the readme tomorrow. Sorry for the delay.

**Comment by kanseaveg** [comment]
Thank you for your patient answers, and thank you for your contributions to the community.

**Comment by kanseaveg** [comment]
@azhx Anything update about README. It's already tomorrow's tomorrow. Thank you.
